version: '2'
services:
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
   hostname: "elasticsearch"
   networks:
     - csv_analysis
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=\"*\""
      - "http.cors.allow-headers=Authorization"
      - "xpack.security.enabled=false"
   ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
   mem_limit: 1g
   cap_add:
   - IPC_LOCK

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.0
    hostname: "kibana"
    networks:
      - csv_analysis
    links:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  csv_analysis:
    # Not using outside this images so far
    external: false